// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzrmmljdccuotupwgkdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6cm1tbGpkY2N1b3R1cHdna2RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODgwNDksImV4cCI6MjA1ODg2NDA0OX0.DBHamqv1BuNs4JpdRWw6MMHipyh1laUZ88Rm91YkFnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);